[build-system]
requires = ["scikit-build-core>=0.10.0"]
build-backend = "scikit_build_core.build"

[project]
name = "culverin"
version = "0.3.0b2"
description = "High-performance Jolt Physics bindings for Python featuring Shadow Buffers and Free-Threading support."
readme = "README.md"
requires-python = ">=3.13"
authors = [
    {name = "Mai Huy Hiếu"}
]
license = {text = "MIT"}
keywords = ["physics", "jolt", "gamedev", "free-threading", "3d", "simulation", "robotics"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: C",
    "Programming Language :: C++",
    "Topic :: Games/Entertainment",
    "Topic :: Scientific/Engineering :: Physics",
]


dependencies = []

[project.urls]
Homepage = "https://github.com/Evilpasture/culverin"
Documentation = "https://github.com/Evilpasture/culverin/tree/master/docs"
Repository = "https://github.com/Evilpasture/culverin.git"
"Bug Tracker" = "https://github.com/Evilpasture/culverin/issues"

[tool.scikit-build]
cmake.build-type = "Release"
cmake.args = [
    "-GNinja",
    # REMOVED: CMAKE_C_COMPILER/CXX_COMPILER (Handled by CI env)
    "-DDOUBLE_PRECISION=ON",
    "-DGENERATE_SAMPLES=OFF",
    "-DGENERATE_UNIT_TESTS=OFF",
    "-DUSE_VULKAN=OFF",
    "-DCMAKE_OSX_DEPLOYMENT_TARGET=13.0",
]

# This ensures the .so/.pyd is placed correctly in the package
wheel.install-dir = "culverin"

# Clean up the wheel - don't ship build artifacts or raw source in the binary wheel
wheel.exclude = [
    "culverin/include/**",
    "culverin/lib/**",
    "culverin/share/**",
    "src/**",
    "**/*.c",
    "**/*.h",
    "**/*.cpp",
    "**/*.obj",
    "**/*.a",
    "**/*.lib",
    "**/*.pdb"
]

# Important for SDIST (Source Distribution)
[tool.scikit-build.sdist]
include = ["culverin/*.pyi", "extern/**", "src/**"]
exclude = ["build/**", "dist/**"]